//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDatabaseWalkthrough
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientsEntities : DbContext
    {
        public PatientsEntities()
            : base("name=PatientsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
    }
}
